[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = '0.8.21'
auto_detect_solc = false
fs_permissions = [
{access = "read", path = "./out"},
]
via-ir = false

[profile.lite.optimizer_details.yulDetails]
optimizerSteps = ''

# See more config options https://github.com/foundry-rs/foundry/tree/master/config